services:
  # Your existing web app
  - type: web
    name: jeopardy-server
    runtime: node
    repo: https://github.com/jelenis/jeopardy-server
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    domains:
      - johnelenis.ca
      - www.johnelenis.ca
    envVars:
      - key: MONGODB_URI
        value: mongodb://mongodb:27017/jeopardydb
    autoDeployTrigger: commit

  # MongoDB service
  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 1
